

// 开始请求
// 主页
export let STATR_FETCH_MAIN_PAGE_DATA = "STATR_FETCH_MAIN_PAGE_DATA";

export let FETCH_MAIN_PAGE_DATA = "FETCH_MAIN_PAGE_DATA";


// 发现
export let STATR_FETCH_DISCOVER_PAGE_DATA = "STATR_FETCH_DISCOVER_PAGE_DATA";

export let FETCH_DISCOVER_PAGE_DATA = "FETCH_DISCOVER_PAGE_DATA";


// 少女漫画
export let STATR_FETCH_GIRL_PAGE_DATA = "STATR_FETCH_GIRL_PAGE_DATA";

export let FETCH_GIRL_PAGE_DATA = "FETCH_GIRL_PAGE_DATA";


// 耽美漫画
export let STATR_FETCH_BEUAUTIFUL_PAGE_DATA = "STATR_FETCH_BEUAUTIFUL_PAGE_DATA";

export let FETCH_BEUAUTIFUL_PAGE_DATA = "FETCH_BEUAUTIFUL_PAGE_DATA";

// 章节
export let STATR_FETCH_CHAPTER_PAGE_DATA = "STATR_FETCH_CHAPTER_PAGE_DATA";

export let FETCH_CHAPTER_PAGE_DATA = "FETCH_CHAPTER_PAGE_DATA";

// 详情
export let STATR_FETCH_DETAIL_PAGE_DATA = "STATR_FETCH_DETAIL_PAGE_DATA";

export let FETCH_DETAIL_PAGE_DATA = "FETCH_DETAIL_PAGE_DATA";
