

// 开始请求
// 少年漫画
export let STATR_FETCH_MAIN_PAGE_DATA = "STATR_FETCH_MAIN_PAGE_DATA";

export let FETCH_MAIN_PAGE_DATA = "FETCH_MAIN_PAGE_DATA";


// 青年漫画
export let STATR_FETCH_DISCOVER_PAGE_DATA = "STATR_FETCH_DISCOVER_PAGE_DATA";

export let FETCH_DISCOVER_PAGE_DATA = "FETCH_DISCOVER_PAGE_DATA";


// 少女漫画
export let STATR_FETCH_GIRL_PAGE_DATA = "STATR_FETCH_GIRL_PAGE_DATA";

export let FETCH_GIRL_PAGE_DATA = "FETCH_GIRL_PAGE_DATA";



//  耽美漫画
export let STATR_FETCH_BEAUTIFUL_PAGE_DATA = "STATR_FETCH_BEAUTIFUL_PAGE_DATA";

export let FETCH_BEAUTIFUL_PAGE_DATA = "FETCH_BEAUTIFUL_PAGE_DATA";


//  Chapter
export let STATR_FETCH_CHAPTER_PAGE_DATA = "STATR_FETCH_CHAPTER_PAGE_DATA";

export let FETCH_CHAPTER_PAGE_DATA = "FETCH_CHAPTER_PAGE_DATA";



//  detail
export let STATR_FETCH_DETAIL_PAGE_DATA = "STATR_FETCH_DETAIL_PAGE_DATA";

export let FETCH_DETAIL_PAGE_DATA = "FETCH_DETAIL_PAGE_DATA";